"""Phase 3 Slice 4 — render a Markdown report from accumulated findings.

``render_report`` is the capstone of the Phase 3 agentic layer: Claude spends
a session calling ``abstract_*`` / ``discover_*`` / ``visualize_*`` tools and
accumulates a narrative plus a list of PNG/SVG/CSV artifact paths. This tool
takes the narrative + artifact list and assembles a Markdown report with:

* H1 title
* ISO-8601 generation timestamp
* The LLM-authored findings body
* An "Artifacts" section linking each file (images are embedded inline; other
  files are listed as links)
* A pm4py-mcp version footer

Pure string assembly — no pm4py calls — so it is fast, offline, and safe.
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path
from typing import Any

from pm4py_mcp import __version__
from pm4py_mcp.errors import WorkspaceError
from pm4py_mcp.server import mcp
from pm4py_mcp.workspace import derived_path, ensure_workspace

_IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp"}


def _resolve_output_path(output_path: str | None) -> Path:
    """Decide where to write the report.

    * ``None`` → unique workspace file like ``report-abc123.md``.
    * Bare filename (no path separators) → workspace directory.
    * Path with separators → used verbatim (absolute or CWD-relative).
    """
    if output_path is None:
        return derived_path("report", "md")

    p = Path(output_path).expanduser()
    out = ensure_workspace() / p if len(p.parts) == 1 else p.resolve()
    if out.suffix.lower() != ".md":
        out = out.with_suffix(".md")
    return out


def _format_artifacts(artifact_paths: list[str]) -> str:
    """Render the artifact list as Markdown, embedding images inline."""
    if not artifact_paths:
        return ""
    lines = ["## Artifacts", ""]
    for raw in artifact_paths:
        p = Path(raw)
        suffix = p.suffix.lower()
        name = p.name
        href = p.as_posix()
        if suffix in _IMAGE_SUFFIXES:
            lines.append(f"![{name}]({href})")
        else:
            lines.append(f"- [{name}]({href})")
        lines.append("")
    return "\n".join(lines)


def _build_report(
    title: str,
    findings: str,
    artifact_paths: list[str] | None,
) -> str:
    generated_at = _dt.datetime.now(tz=_dt.timezone.utc).isoformat(timespec="seconds")
    parts = [
        f"# {title}",
        "",
        f"*Generated {generated_at} by pm4py-mcp {__version__}.*",
        "",
        findings.strip(),
        "",
    ]
    artifacts_block = _format_artifacts(artifact_paths or [])
    if artifacts_block:
        parts.append(artifacts_block)
    parts.extend(
        [
            "---",
            "",
            f"Report generated by `pm4py-mcp` v{__version__}.",
            "",
        ]
    )
    return "\n".join(parts)


@mcp.tool()
def render_report(
    title: str,
    findings: str,
    artifact_paths: list[str] | None = None,
    output_path: str | None = None,
) -> dict[str, Any]:
    """Assemble a Markdown executive report from prose findings + artifact links.

    Parameters
    ----------
    title
        Report heading. Rendered as an H1.
    findings
        Markdown-formatted narrative. Pass the prose the LLM wrote after
        calling ``abstract_*`` / ``get_*`` tools — bullet points, tables,
        paragraphs all work. Leading/trailing whitespace is stripped.
    artifact_paths
        Optional list of absolute paths to PNG/SVG/CSV files produced
        earlier in the session (e.g. by ``visualize_petri_net`` or
        ``export_log``). Images are embedded inline; other files are
        listed as links.
    output_path
        Optional. Bare filename lands in the workspace; a path with
        separators is honored as-is. When omitted, writes to a unique
        file like ``report-abc123.md`` in the workspace.

    Returns
    -------
    dict
        ``{"path": str, "size_bytes": int, "num_artifacts": int}``.
    """
    if not title.strip():
        raise WorkspaceError("Report title must be non-empty.")
    if not findings.strip():
        raise WorkspaceError("Report findings must be non-empty.")

    out = _resolve_output_path(output_path)
    try:
        out.parent.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise WorkspaceError(f"Could not create output directory {out.parent}: {exc}") from exc

    body = _build_report(title, findings, artifact_paths)
    try:
        out.write_text(body, encoding="utf-8")
    except OSError as exc:
        raise WorkspaceError(f"Could not write report to {out}: {exc}") from exc

    return {
        "path": str(out),
        "size_bytes": out.stat().st_size,
        "num_artifacts": len(artifact_paths or []),
    }


__all__ = ["render_report"]
